In [1]:
%matplotlib inline
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import logm

In [2]:
## parameters, UD=underdamped, OD=overdamped
N   = 2**20            # # of data points
m   = 1                # mass
T   = 1                # temperature
k   = 1                # stiffness
k_B = 1                # Boltzmann constant
f_s = 1             # sampling frequency
dt  = 1/f_s            # step size
g_c = np.sqrt(4*m*k)   # gamma critical
g_f = .5               # <1 for UD and >1 for OD
g   = g_c*g_f          # gamma
w0  = np.sqrt(k/m)     # frequency of UD motion
tau = m/g              # relaxation time
D   = k_B*T/g          # diffusion constant

if g_f >1:
    w = 1j*np.sqrt(-(w0**2)+(1/(4*tau*tau))) 
else:
    w = np.sqrt((w0**2)-(1/(4*tau*tau)))

params = (N, dt, w, w0, tau, D, k, m, k_B, T)

In [16]:
def calcSigma(params):
    N, dt, w, w0, tau, D, k, m, k_B, T = params
    imw=1/(m*w*w);   dtbt=-dt/tau; ee=np.exp(dtbt);  dd=D/(w*w*tau*tau);  
    tt   = w*dt;   cc  = np.cos(tt);  ss=np.sin(tt)
    
    s1 = (k_B*T)*( 1/k -ee*(imw*ss*ss +(cc + ss/(2*w*tau))**2 ))
    s2 = dd*ee*ss*ss
    s3 = (k_B*T/m)*( 1 -ee*(imw*ss*ss +(cc-ss/(2*w*tau))**2 )) 
    return np.real(s1), np.real(s3), np.real(s2)    


def calcLambda(params):
    N, dt, w, w0, tau, D, k, m, k_B, T = params
    ii  = np.eye(2)
    ll = np.asanyarray([[0, -1], [k/m, g/m]])
    ee = np.exp(-dt/(2*tau)); wt2=2*w*tau
    cc=np.cos(w*dt); ss=np.sin(w*dt) 
    
    Lambda = ee*((cc+ss/wt2)*ii - ll*ss/w ) 
    return np.real(Lambda)


def calcXV(params, Lambda, Sigma):
    N, dt, w, w0, tau, D, k, m, k_B, T = params
    x = np.zeros([N,1])
    v = np.zeros([N,1])
    
    s1, s3, s2 = Sigma

    for j in np.arange(0,N-1):
        oldvec = np.array([x[j],v[j]])
        randgauss = np.random.randn(2,1)
        delx = np.sqrt(s1)*randgauss[0]
        delv = (s2/(np.sqrt(s1)))*randgauss[0]+(np.sqrt(s3 - ((s2**2)/(s1))))*randgauss[1]
        delvec = np.array([delx,delv])
        updatevec = np.dot(Lambda,oldvec)+delvec
        x[j+1] = updatevec[0]
        v[j+1] = updatevec[1]
    return x,v

In [17]:
params = (N, dt, w, w0, tau, D, k, m, k_B, T)
Lambda = calcLambda(params)
Sigma  = calcSigma(params)
x, v   = calcXV(params, Lambda, Sigma)

In [18]:
#plt.plot(x);plt.plot(v);

## Bayes I

In [19]:
# matrix sufficient statistics
T1_11 = np.sum(x[1:]**2)
T1_12 = np.sum(x[1:]*v[1:])
T1_21 = T1_12
T1_22 = np.sum(v[1:]**2)

T2_11 = np.sum(x[1:]*x[:-1])
T2_12 = np.sum(x[1:]*v[:-1])
T2_21 = np.sum(v[1:]*x[:-1])
T2_22 = np.sum(v[1:]*v[:-1])

T3_11 = np.sum(x[:-1]*x[:-1])
T3_12 = np.sum(x[:-1]*v[:-1])
T3_21 = T3_12
T3_22 = np.sum(v[:-1]*v[:-1])

T1    = np.asanyarray([[T1_11, T1_12],[T1_21, T1_22]])
T2    = np.asanyarray([[T2_11, T2_12],[T2_21, T2_22]])
T3    = np.asanyarray([[T3_11, T3_12],[T3_21, T3_22]])

In [20]:
#MAP estimate of Lambda and Sigma

invT3     = np.linalg.inv(T3)
LambdaMAP = np.dot(T2, invT3)
SigmaMAP  = (1/N)*( T1 - np.dot( T2, np.dot(invT3, T2.transpose()) ) )

In [21]:
#MAP estimate of c using Onsager-Casimir symmetry

L_t  = LambdaMAP.transpose()
eps  = np.asanyarray([[1,0],[0,-1]])

L_te = np.dot(eps, L_t)
Lte2 = np.dot(L_te, L_te)

II   = np.eye(2)
cc   = np.linalg.inv(II - Lte2)
cMAP = np.dot(SigmaMAP, cc)

print LambdaMAP, '\n', SigmaMAP, '\n', cMAP

[[ 0.65965408  0.53222908]
 [-0.53335043  0.12380123]] 
[[ 0.27981719  0.28433134]
 [ 0.28433134  0.69915979]] 
[[  9.96489701e-01  -6.60345422e-04]
 [ -1.17877250e-03   9.98127931e-01]]


In [22]:
#MAP estimate of k and m and gamma

ll = -logm(LambdaMAP)/dt

m_MAP = k_B*T/cMAP[1,1]
k_MAP = k_B*T/cMAP[0,0]
g_MAP = m*ll[1,1]


print m_MAP, k_MAP, g_MAP

1.00187557994 1.00352266496 1.00699942073


In [23]:
Tl = LambdaMAP
ll = -logm(LambdaMAP)/dt
Tc = k_B*T*(np.dot((II - Lte2), np.linalg.inv(SigmaMAP)))

In [24]:
print Tc[0, 0], Tc[1, 1], Tc[1, 1]*ll[1,1] 
print
print k, m, g

1.00352345033 1.00187636402 1.0088889182

1 1 1.0


## Bayes II

In [25]:
#MAP estimate of c using Bayes II
c_B2 = T3/N
print c_B2

[[  9.95502413e-01  -1.47734588e-04]
 [ -1.47734588e-04   9.97652648e-01]]
